# Generated by Django 6.0.4 on 2026-05-07 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_id_student_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeralaAcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language1', models.CharField(max_length=5)),
                ('language2', models.CharField(max_length=5)),
                ('english', models.CharField(max_length=5)),
                ('hindi', models.CharField(max_length=5)),
                ('social_science', models.CharField(max_length=5)),
                ('physics', models.CharField(max_length=5)),
                ('chemistry', models.CharField(max_length=5)),
                ('biology', models.CharField(max_length=5)),
                ('mathematics', models.CharField(max_length=5)),
                ('it', models.CharField(max_length=5)),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kerala_details', to='accounts.student')),
            ],
        ),
    ]
