# Generated by Django 6.0.4 on 2026-05-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_keralaacademicdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncc_nss_spc', models.BooleanField(default=False)),
                ('ncc_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('sports_district', models.BooleanField(default=False)),
                ('sports_state', models.BooleanField(default=False)),
                ('sports_national', models.BooleanField(default=False)),
                ('sports_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('youth_district', models.BooleanField(default=False)),
                ('youth_state', models.BooleanField(default=False)),
                ('youth_national', models.BooleanField(default=False)),
                ('youth_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracurricular', to='accounts.student')),
            ],
        ),
    ]
