# Generated by Django 6.0.4 on 2026-05-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extracurricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref1', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Bio-Mathematics', 'Bio-Mathematics'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=50)),
                ('pref2', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Bio-Mathematics', 'Bio-Mathematics'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=50)),
                ('pref3', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Bio-Mathematics', 'Bio-Mathematics'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_preference', to='accounts.student')),
            ],
        ),
    ]
