# Generated by Django 6.0.4 on 2026-05-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coursepreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='register_number',
        ),
    ]
