# Generated by Django 6.0.4 on 2026-05-07 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_coursepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Bio-Mathematics', 'Bio-Mathematics'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=50)),
                ('index_mark', models.FloatField(default=0)),
                ('bonus_mark', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
