# Generated by Django 6.0.4 on 2026-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='stream_score',
            field=models.FloatField(default=0),
        ),
    ]
