# Generated by Django 6.0.4 on 2026-05-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_admissionresult_stream_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='preference_order',
            field=models.IntegerField(default=1),
        ),
    ]
