# Generated by Django 6.0.4 on 2026-05-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_admissionresult_preference_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='allotted',
            field=models.BooleanField(default=False),
        ),
    ]
