# Generated by Django 6.0.4 on 2026-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_admissionresult_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
