# Generated by Django 6.0.4 on 2026-05-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_admissionresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionresult',
            name='status',
        ),
    ]
